services:
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    container_name: fastapi_dev
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_PASSWORD: app_pass
      DB_PORT: "3306"
      DB_USER: appuser
      MYSQL_SSL_MODE: DISABLED
      PYTHONPATH: /app
      WATCHFILES_FORCE_POLLING: "true" # mac/リモートFS対策
    volumes:
      - ./app:/app/app # ローカルを上書きマウント（開発用）
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command:
      - .venv/bin/python
      - -m
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  db:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u${DB_USER}",
          "-p${DB_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  db_data:
